### ISSUE TITLE
Fatal error when clue/php-stream-filter is loaded in 2 different projects

### ISSUE THREAD

**Issue by strategio** [clue/php-stream-filter#26]
We have several projects that runs together, and more than one project is using `clue/php-stream-filter`. This causes a fatal error:

`Fatal error: Cannot redeclare Clue\StreamFilter\append() (previously declared in...`

The reason is that we will load the same functions in the same namespace at 2 different places.

Before to define a function, we need to check if it does not already exists, like in this project https://github.com/tightenco/collect/blob/laravel-5.8-ongoing/src/Collect/Support/helpers.php#L7.

**Comment by strategio** [comment]
I just found out that this has been addressed few days ago in https://github.com/clue/php-stream-filter/commit/4807295685ab3ac0619b9e54d5b886877a25500a.

Sorry for the noise, closing :)

**Comment by clue** [comment]
No worries and thanks for reporting back and confirming that the latest v1.4.1 release should address this very issue :)

**Comment by phaberest** [comment]
I'm still getting this error, could you please tag the fix?

**Comment by clue** [comment]
This has been addressed via #23 which has been released as `v1.4.1` a while ago. Are you sure you're running the latest version?

**Comment by phaberest** [comment]
Forget it, thank you @clue! It was due to an older version in another composer inside a plugin subfolder.

Solved by upgrading it 👍
